Repository Lazap-Development/Lazap, pull requests merged in 2023-02, with the labels that each got.

#122 v0.6.2 Release Candidiate
  README.md
  package.json
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/src/main.rs
  src-tauri/tauri.conf.json
  src/App.vue
  src/assets/img/default-game-banner.png
  src/assets/img/radeon.png
  src/assets/svg/discord.svg
  src/components/AllGames.vue
  src/components/LeftBar.vue
  src/components/Settings.vue
  src/components/Titlebar.vue
  src/components/find-games.vue
  src/components/launchers/EpicGames.js
  src/components/launchers/Lutris.js
  src/components/launchers/Minecraft.js
  src/components/launchers/RiotGames.js
  src/components/launchers/RockstarGames.js
  src/components/launchers/Steam.js
  src/components/launchers/Uplay.js
  src/components/launchers/XboxGames.js
  src/components/launchers/find-games.js
  src/components/listeners.vue
  src/components/modules/banners.js
  src/components/modules/icons.js
  src/components/modules/rpcOptions.js
  src/components/storage.vue
  src/css/default.css
  src/main.js
  yarn.lock
Labels: huge feature, linux, macos, version, adequate

#123 Commit(s) that were left out for v0.6.2 release
  src-tauri/Cargo.toml
  src-tauri/src/main.rs
  src-tauri/tauri.conf.json
  src/components/AllGames.vue
Labels: bug fix

#114 feat(app): Add auto-update feature to the app
  .gitignore
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/src/main.rs
  src-tauri/tauri.conf.json
  src/App.vue
  src/assets/svg/discord.svg
  src/assets/svg/download.svg
  src/components/Settings.vue
  src/components/Titlebar.vue
Labels: enhancement, help wanted, win, linux, adequate
